server:
    port: 9092
spring:
    application:
        name: trail-provider-service
    rabbitmq:
        port: 5672
        virtual-host: /
        host: localhost
        username: guest
        password: guest
