server:
    port: 9093
spring:
    application:
        name: attack-generation-service
    rabbitmq:
        port: 5672
        virtual-host: vhost
        host: localhost
        username: guest
        password: guest
