services:
  eureka:
    container_name: eureka
    build: ../eureka
    image: myron0220/eureka
    environment:
      - eureka.instance.ipAddress="127.0.0.1"
    ports:
      - "8761:8761"

  rabbit-mq:
    container_name: rabbit-mq
    image: rabbitmq:management
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_PORT=5672
    ports:
      - "5672:5672"
      - "15672:15672"

  game-centre-srv:
    container_name: game-centre-srv
    build: ../game-centre-srv
    image: myron0220/game-centre-srv
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka
      - spring.rabbitmq.host=rabbit-mq
      - spring.rabbitmq.virtual-host=/
    ports:
      - "9090:9090"
    depends_on:
      - eureka
      - rabbit-mq

  point-srv:
    container_name: point-srv
    build: ../point-srv
    image: myron0220/point-srv
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka
      - spring.rabbitmq.host=rabbit-mq
      - spring.rabbitmq.virtual-host=/
    ports:
      - "9094:9094"
    depends_on:
      - eureka
      - rabbit-mq

  trail-provider-srv:
    container_name: trail-provider-srv
    build: ../trail-provider-srv
    image: myron0220/trail-provider-srv
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka
      - spring.rabbitmq.host=rabbit-mq
      - spring.rabbitmq.virtual-host=/
    ports:
      - "9092:9092"
    depends_on:
      - eureka
      - rabbit-mq

  attack-generation-srv:
    container_name: attack-generation-srv
    build: ../attack-generation-srv
    image: myron0220/attack-generation-srv
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka
      - spring.rabbitmq.host=rabbit-mq
      - spring.rabbitmq.virtual-host=/
    ports:
      - "9093:9093"
    depends_on:
      - eureka
      - rabbit-mq
      - heartrate-monitor-srv

  heartrate-monitor-srv:
    container_name: heartrate-monitor-srv
    build: ../heartrate-monitor-srv
    image: myron0220/heartrate-monitor-srv
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka
      - spring.rabbitmq.host=rabbit-mq
      - spring.rabbitmq.virtual-host=/
    ports:
      - "9091:9091"
    depends_on:
      - eureka
      - rabbit-mq
      - game-centre-srv
      - trail-provider-srv
      - point-srv






